# Generated by Django 4.0.5 on 2022-07-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='identifier',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
    ]
